### ISSUE TITLE
Problema con la página

### ISSUE THREAD

**Issue by CarlosRubioTNM** [CarlosRubioTNM/HolaGithub#1]
No me gustó que la página principal no tiene encabezado.

**Comment by CarlosRubioTNM** [comment]
Gracias por tu comentario, cambiaremos el contenido de la página.

**Comment by CarlosRubioTNM** [comment]
Encárgate tú, @CarlosRubioTNM

**Comment by NeSp1n** [comment]
hola

**Comment by Beto1807** [comment]
Fragmentao

**Comment by CarlosRubioTNM** [comment]
Cambio aplicado.
