### ISSUE TITLE
Error en la visualización del README

### ISSUE THREAD

**Issue by RayadoxAV** [CarlosRubioTNM/HolaGithub#2]
La imagen de ejemplo del README no tiene una liga correcta, por lo que se ve así:
![image](https://user-images.githubusercontent.com/49849531/154151419-d182d420-c154-4322-8f68-ad6fdb2ecb77.png)
Espero que lo arreglen pronto, es mi repositorio favorito

**Comment by CarlosRubioTNM** [comment]
No

**Comment by CarlosRubioTNM** [comment]
Bueno pues

**Comment by CarlosRubioTNM** [comment]
Listo
